import type { Attendee, CreateAttendeeInput, Room } from "./types";
import { generateId } from "./utils";

export const DEMO_ROOM_SLUG = "demo";

export const demoRoom: Room = {
  id: "demo-room",
  slug: DEMO_ROOM_SLUG,
  name: "Startup Mixer 2026",
  organizerName: "Essam",
  description: "A networking night for builders and founders.",
  createdAt: new Date().toISOString(),
  status: "live",
  isPublic: true,
};

export const demoAttendees: Attendee[] = [
  {
    id: "aisha-khan",
    roomId: "demo-room",
    name: "Aisha Khan",
    email: "aisha@example.com",
    role: "ML Student",
    company: "UCalgary",
    interests: ["AI", "Robotics", "Computer Vision"],
    lookingFor: "ML internship leads",
    canHelpWith: "Model evaluation and Python",
    cluster: "Students",
    createdAt: new Date().toISOString(),
  },
  {
    id: "marcus-lee",
    roomId: "demo-room",
    name: "Marcus Lee",
    email: "marcus@example.com",
    role: "Founder",
    company: "Nova Labs",
    interests: ["Startups", "AI", "Product"],
    lookingFor: "Technical cofounder",
    canHelpWith: "Pitch strategy",
    cluster: "Founders",
    createdAt: new Date().toISOString(),
  },
  {
    id: "priya-shah",
    roomId: "demo-room",
    name: "Priya Shah",
    email: "priya@example.com",
    role: "Recruiter",
    company: "Northstar Tech",
    interests: ["Hiring", "Software Engineering", "Internships"],
    lookingFor: "Strong student builders",
    canHelpWith: "Resume feedback",
    cluster: "Recruiters",
    createdAt: new Date().toISOString(),
  },
  {
    id: "daniel-kim",
    roomId: "demo-room",
    name: "Daniel Kim",
    email: "daniel@example.com",
    role: "Designer",
    company: "Freelance",
    interests: ["UX", "Branding", "Startups"],
    lookingFor: "Founder projects",
    canHelpWith: "Landing page design",
    cluster: "Designers",
    createdAt: new Date().toISOString(),
  },
  {
    id: "sarah-chen",
    roomId: "demo-room",
    name: "Sarah Chen",
    email: "sarah@example.com",
    role: "Software Engineer",
    company: "Stripe",
    interests: ["AI", "Distributed Systems", "Startups"],
    lookingFor: "Side project collaborators",
    canHelpWith: "Backend architecture",
    cluster: "Engineers",
    createdAt: new Date().toISOString(),
  },
  {
    id: "james-okonkwo",
    roomId: "demo-room",
    name: "James Okonkwo",
    email: "james@example.com",
    role: "PhD Researcher",
    company: "MIT",
    interests: ["AI", "Research", "Computer Vision"],
    lookingFor: "Industry partnerships",
    canHelpWith: "Research collaboration",
    cluster: "Researchers",
    createdAt: new Date().toISOString(),
  },
  {
    id: "elena-rodriguez",
    roomId: "demo-room",
    name: "Elena Rodriguez",
    email: "elena@example.com",
    role: "Product Manager",
    company: "Figma",
    interests: ["Product", "Design", "Startups"],
    lookingFor: "Early-stage founders",
    canHelpWith: "Product strategy",
    cluster: "Founders",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tyler-wong",
    roomId: "demo-room",
    name: "Tyler Wong",
    email: "tyler@example.com",
    role: "CS Student",
    company: "UCalgary",
    interests: ["AI", "Startups", "Web Development"],
    lookingFor: "Hackathon teammates",
    canHelpWith: "Full-stack development",
    cluster: "Students",
    createdAt: new Date().toISOString(),
  },
  {
    id: "nina-patel",
    roomId: "demo-room",
    name: "Nina Patel",
    email: "nina@example.com",
    role: "VC Associate",
    company: "Horizon Ventures",
    interests: ["Startups", "AI", "Investing"],
    lookingFor: "Pre-seed founders",
    canHelpWith: "Fundraising advice",
    cluster: "Recruiters",
    createdAt: new Date().toISOString(),
  },
  {
    id: "alex-morrison",
    roomId: "demo-room",
    name: "Alex Morrison",
    email: "alex@example.com",
    role: "DevOps Engineer",
    company: "AWS",
    interests: ["Cloud", "Distributed Systems", "Startups"],
    lookingFor: "Infrastructure challenges",
    canHelpWith: "Cloud architecture",
    cluster: "Engineers",
    createdAt: new Date().toISOString(),
  },
  {
    id: "maya-johnson",
    roomId: "demo-room",
    name: "Maya Johnson",
    email: "maya@example.com",
    role: "UX Researcher",
    company: "Google",
    interests: ["UX", "Research", "AI"],
    lookingFor: "Design partners",
    canHelpWith: "User research methods",
    cluster: "Researchers",
    createdAt: new Date().toISOString(),
  },
  {
    id: "ryan-foster",
    roomId: "demo-room",
    name: "Ryan Foster",
    email: "ryan@example.com",
    role: "Founder",
    company: "HealthAI",
    interests: ["AI", "Healthcare", "Startups"],
    lookingFor: "ML engineers",
    canHelpWith: "Healthcare domain expertise",
    cluster: "Founders",
    createdAt: new Date().toISOString(),
  },
  {
    id: "lisa-wang",
    roomId: "demo-room",
    name: "Lisa Wang",
    email: "lisa@example.com",
    role: "Brand Designer",
    company: "Studio L",
    interests: ["Branding", "Design", "Startups"],
    lookingFor: "Startup clients",
    canHelpWith: "Visual identity",
    cluster: "Designers",
    createdAt: new Date().toISOString(),
  },
  {
    id: "omar-hassan",
    roomId: "demo-room",
    name: "Omar Hassan",
    email: "omar@example.com",
    role: "Data Science Student",
    company: "UCalgary",
    interests: ["AI", "Data Science", "Research"],
    lookingFor: "Research mentors",
    canHelpWith: "Data analysis",
    cluster: "Students",
    createdAt: new Date().toISOString(),
  },
  {
    id: "kate-sullivan",
    roomId: "demo-room",
    name: "Kate Sullivan",
    email: "kate@example.com",
    role: "Talent Lead",
    company: "Shopify",
    interests: ["Hiring", "Startups", "Product"],
    lookingFor: "Senior engineers",
    canHelpWith: "Interview prep",
    cluster: "Recruiters",
    createdAt: new Date().toISOString(),
  },
  {
    id: "david-park",
    roomId: "demo-room",
    name: "David Park",
    email: "david@example.com",
    role: "Mobile Engineer",
    company: "Spotify",
    interests: ["Mobile", "Startups", "Design"],
    lookingFor: "iOS side projects",
    canHelpWith: "Swift and React Native",
    cluster: "Engineers",
    createdAt: new Date().toISOString(),
  },
  {
    id: "rachel-green",
    roomId: "demo-room",
    name: "Rachel Green",
    email: "rachel@example.com",
    role: "Research Scientist",
    company: "DeepMind",
    interests: ["AI", "Research", "Robotics"],
    lookingFor: "Academic collaborators",
    canHelpWith: "Paper reviews",
    cluster: "Researchers",
    createdAt: new Date().toISOString(),
  },
  {
    id: "chris-bell",
    roomId: "demo-room",
    name: "Chris Bell",
    email: "chris@example.com",
    role: "Founder",
    company: "GreenTech",
    interests: ["Startups", "Climate", "Product"],
    lookingFor: "Climate tech engineers",
    canHelpWith: "Sustainability strategy",
    cluster: "Founders",
    createdAt: new Date().toISOString(),
  },
  {
    id: "jenny-liu",
    roomId: "demo-room",
    name: "Jenny Liu",
    email: "jenny@example.com",
    role: "Product Designer",
    company: "Airbnb",
    interests: ["UX", "Design", "Startups"],
    lookingFor: "Design system work",
    canHelpWith: "Design critiques",
    cluster: "Designers",
    createdAt: new Date().toISOString(),
  },
  {
    id: "mike-thompson",
    roomId: "demo-room",
    name: "Mike Thompson",
    email: "mike@example.com",
    role: "MBA Student",
    company: "Haskayne",
    interests: ["Startups", "Investing", "Product"],
    lookingFor: "Technical cofounders",
    canHelpWith: "Business development",
    cluster: "Students",
    createdAt: new Date().toISOString(),
  },
];

export function createDemoAttendees(roomId: string): Attendee[] {
  return demoAttendees.map((a) => ({
    ...a,
    id: generateId(),
    roomId,
    createdAt: new Date().toISOString(),
  }));
}

export function getSampleAttendees(): CreateAttendeeInput[] {
  return demoAttendees.map(({ id, roomId, createdAt, sessionToken, claimedBy, profileId, ...rest }) => {
    void id;
    void roomId;
    void createdAt;
    void sessionToken;
    void claimedBy;
    void profileId;
    return rest;
  });
}
